XCOPY "C:\vb.net\UFCW.CMS\UFCW.CMS.PROVIDER\ProviderDAL\bin\UFCW.CMS.ProviderDAL.*" "C:\vb.net\UFCW.CMS\UFCW.CMS.PROVIDER\Provider\bin\*.*" /y
XCOPY "C:\vb.net\UFCW.CMS\UFCW.CMS.PROVIDER\ExtendedErrorProvider\bin\UFCW.CMS.ExtendedErrorProvider.*" "C:\vb.net\UFCW.CMS\UFCW.CMS.PROVIDER\Provider\bin\*.*" /y
XCOPY "C:\vb.net\UFCW.CMS\UFCW.CMS.PROVIDER\ProviderWork\bin\UFCW.CMS.ProviderWork.*" "C:\vb.net\UFCW.CMS\UFCW.CMS.PROVIDER\Provider\bin\*.*" /y
XCOPY "C:\vb.net\UFCW.CMS\UFCW.CMS.PROVIDER\ProviderWork\*.xml" "C:\vb.net\UFCW.CMS\UFCW.CMS.PROVIDER\Provider\bin\*.*" /y
XCOPY "C:\vb.net\UFCW.CMS\UFCW.CMS.PROVIDER\ProviderSearch\*.xml" "C:\vb.net\UFCW.CMS\UFCW.CMS.PROVIDER\Provider\bin\*.*" /y
XCOPY "C:\vb.net\UFCW.CMS\UFCW.CMS.PROVIDER\ProviderSearch\bin\UFCW.CMS.ProviderSearch.*" "C:\vb.net\UFCW.CMS\UFCW.CMS.PROVIDER\Provider\bin\*.*" /y
XCOPY "C:\vb.net\UFCW.CMS\UFCW.CMS.PROVIDER\ProviderMain.Configuration\bin\UFCW.CMS.ProviderConfiguration*" "C:\vb.net\UFCW.CMS\UFCW.CMS.PROVIDER\Provider\bin\*.*" /y
XCOPY "C:\vb.net\UFCW.CMS\UFCW.CMS.PROVIDER\Provider\*.config" "C:\vb.net\UFCW.CMS\UFCW.CMS.PROVIDER\Provider\bin\*.*" /y
XCOPY "C:\vb.net\UFCW.CMS\UFCW.CMS.PROVIDER\Provider\*.key" "C:\vb.net\UFCW.CMS\UFCW.CMS.PROVIDER\Provider\bin\*.*" /y
XCOPY "C:\VB.NET\bin\*.*" "C:\vb.net\UFCW.CMS\UFCW.CMS.PROVIDER\Provider\bin\*.*" /y
